//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.EncodingServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EncodingServiceRef.IEncodingService")]
    public interface IEncodingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncodingService/ProcessJob", ReplyAction="http://tempuri.org/IEncodingService/ProcessJobResponse")]
        long ProcessJob(Common.Entities.JobDetails j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncodingService/ProcessJob", ReplyAction="http://tempuri.org/IEncodingService/ProcessJobResponse")]
        System.Threading.Tasks.Task<long> ProcessJobAsync(Common.Entities.JobDetails j);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEncodingServiceChannel : Client.EncodingServiceRef.IEncodingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EncodingServiceClient : System.ServiceModel.ClientBase<Client.EncodingServiceRef.IEncodingService>, Client.EncodingServiceRef.IEncodingService {
        
        public EncodingServiceClient() {
        }
        
        public EncodingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EncodingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncodingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncodingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long ProcessJob(Common.Entities.JobDetails j) {
            return base.Channel.ProcessJob(j);
        }
        
        public System.Threading.Tasks.Task<long> ProcessJobAsync(Common.Entities.JobDetails j) {
            return base.Channel.ProcessJobAsync(j);
        }
    }
}
